# Tugas 3 | Preprocessing

Tugas 3 ini tujuannya untuk Preprocessing:

Dataset: detik_berita_2024.csv & pta_mulitT_full.csv

Tahapan: hapus stopwords -> hapus simbol -> spellcheck
-> stemming -> tokenisasi -> simpan hasil ke CSV

## Install library yang digunakan

In [1]:
import sys
!{sys.executable} -m pip install sastrawi
!{sys.executable} -m pip install pyspellchecker 
!{sys.executable} -m pip install regex
!{sys.executable} -m pip install nltk

import pandas as pd
import re
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from spellchecker import SpellChecker
import nltk

Requirement already satisfied: sastrawi in c:\users\endyzan\appdata\local\programs\python\python313\lib\site-packages (1.0.1)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pyspellchecker in c:\users\endyzan\appdata\local\programs\python\python313\lib\site-packages (0.8.3)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: regex in c:\users\endyzan\appdata\local\programs\python\python313\lib\site-packages (2024.11.6)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: nltk in c:\users\endyzan\appdata\local\programs\python\python313\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\endyzan\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in c:\users\endyzan\appdata\local\programs\python\python313\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\endyzan\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\endyzan\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\endyzan\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip

## Load Dataset

- detik_berita_2024.csv  -> berisi berita hasil crawling dari portal Detik.com
- pta_mulitT_full.csv    -> berisi abstrak skripsi dari repository PTA Trunojoyo

In [3]:
detik = pd.read_csv("detik_berita_2024.csv")
pta   = pd.read_csv("pta_mulitT_full.csv")

print("Detik shape:", detik.shape)
print("PTA shape:", pta.shape)

print(detik.head())
print(pta.head())

Detik shape: (100, 5)
PTA shape: (2286, 5)
                                        Judul Berita  \
0  Marcus Gideon ke Ganda Pratama : Enggak Bisa S...
1  Megawati Tampil Gemilang, Red Sparks Gebuk IBK...
2  Punya Tim & Semangat Baru, Jakarta Pertamina E...
3  Jakarta Pertamina Enduro Tak Mau Lagi Cuma Gas...
4  Ducati ke Honda: Bangun Motor Butuh Waktu, Tak...

                                                Link  Kategori     Tanggal  \
0  https://sport.detik.com/raket/d-7712417/marcus...  Olahraga  2024-12-31
1  https://sport.detik.com/sport-lain/d-7712305/m...  Olahraga  2024-12-31
2  https://sport.detik.com/sport-lain/d-7712206/p...  Olahraga  2024-12-31
3  https://sport.detik.com/sport-lain/d-7712029/j...  Olahraga  2024-12-31
4  https://sport.detik.com/moto-gp/d-7711970/duca...  Olahraga  2024-12-31

                                          Isi Berita
0  Marcus Fernaldi Gideonhadir di PelatnasPBSI. K...
1  Megawati Hangestri PertiwimembawaRed Sparksmer...
2  Tahun ini, tim Pertamina Jakarta Pertamina End...
3  SetterJakarta Pertamina Enduro(JPE) Tisya Amal...
4  Ducatimemberi wanti-wanti keHondamenjelang mus...
                 penulis                                              judul  \
0     A.Ubaidillah S.Kom  PERANCANGAN DAN IMPLEMENTASI SISTEM DATABASE \...
1    M. Basith Ardianto,  APLIKASI KONTROL DAN MONITORING JARINGAN KOMPU...
2  Akhmad Suyandi, S.Kom  RANCANG BANGUN APLIKASI PROXY SERVER UNTUK\r\n...
3   Septian Rahman Hakim  SISTEM AUGMENTED REALITY ANIMASI BENDA BERGERA...
4        Heri Supriyanto  SISTEM PENDUKUNG KEPUTUSAN OPTIMASI PENJADWALA...

              pembimbing_pertama           pembimbing_kedua  \
0               Budi Setyono M.T               Hermawan S.T
1          Drs. Budi Soesilo, MT              Koko Joni, ST
2         Drs. Budi Soesilo, M.T           Hermawan, ST, MT
3  Arik Kurniawati, S.Kom., M.T.       Haryanto, S.T., M.T.
4           Mulaab, S.Si., M.Kom  Firli Irhamni, ST., M.Kom

                                             abstrak
0  Sistem  informasi  akademik  (SIAKAD) merupaka...
1  Berjalannya koneksi jaringan komputer dengan l...
2  Web server adalah sebuah perangkat lunak serve...
3  Seiring perkembangan teknologi yang ada diduni...
4  Penjadwalan  kuliah  di  Perguruan  Tinggi  me...

## Stopword

Menghapus *stopwords* (kata-kata umum seperti "yang", "dan", "di") karena biasanya tidak menambah makna signifikan.

In [4]:
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')
stop_words = set(stopwords.words('indonesian'))

def remove_stopwords(text):
    tokens = word_tokenize(str(text))
    filtered = [w for w in tokens if not w.lower() in stop_words]
    return " ".join(filtered)

detik["clean_no_stopword"] = detik["Isi Berita"].apply(remove_stopwords)
pta["clean_no_stopword"]   = pta["abstrak"].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\endyzan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\endyzan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\endyzan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

### Hasil Stopword

#### berita

In [10]:
detik[["Isi Berita", "clean_no_stopword"]].head(5)

,Isi Berita,clean_no_stopword
0,Marcus Fernaldi Gideonhadir di PelatnasPBSI. K...,Marcus Fernaldi Gideonhadir PelatnasPBSI . Ked...
1,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...
2,"Tahun ini, tim Pertamina Jakarta Pertamina End...",", tim Pertamina Jakarta Pertamina Enduro ( JPE..."
3,SetterJakarta Pertamina Enduro(JPE) Tisya Amal...,SetterJakarta Pertamina Enduro ( JPE ) Tisya A...
4,Ducatimemberi wanti-wanti keHondamenjelang mus...,Ducatimemberi wanti-wanti keHondamenjelang mus...

#### pta.trunojoyo.ac.id

In [9]:
pta[["abstrak", "clean_no_stopword"]].head(5)

,abstrak,clean_no_stopword
0,Sistem informasi akademik (SIAKAD) merupaka...,Sistem informasi akademik ( SIAKAD ) sistem in...
1,Berjalannya koneksi jaringan komputer dengan l...,Berjalannya koneksi jaringan komputer lancar g...
2,Web server adalah sebuah perangkat lunak serve...,Web server perangkat lunak server berfungsi me...
3,Seiring perkembangan teknologi yang ada diduni...,"Seiring perkembangan teknologi didunia , muncu..."
4,Penjadwalan kuliah di Perguruan Tinggi me...,Penjadwalan kuliah Perguruan kompleks . permas...

## Menghilangkan Symbol/Tanda Baca

Menghapus simbol/tanda baca agar teks hanya berisi huruf dan angka.

In [11]:
def remove_symbols(text):
    return re.sub(r'[^A-Za-z0-9\s]', '', str(text))

detik["clean_no_symbol"] = detik["clean_no_stopword"].apply(remove_symbols)
pta["clean_no_symbol"]   = pta["clean_no_stopword"].apply(remove_symbols)

### Hasil menghilangkan Symbol/tanda baca

#### berita

In [12]:
detik[["Isi Berita", "clean_no_stopword", "clean_no_symbol"]].head(5)

,Isi Berita,clean_no_stopword,clean_no_symbol
0,Marcus Fernaldi Gideonhadir di PelatnasPBSI. K...,Marcus Fernaldi Gideonhadir PelatnasPBSI . Ked...,Marcus Fernaldi Gideonhadir PelatnasPBSI Keda...
1,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...
2,"Tahun ini, tim Pertamina Jakarta Pertamina End...",", tim Pertamina Jakarta Pertamina Enduro ( JPE...",tim Pertamina Jakarta Pertamina Enduro JPE ...
3,SetterJakarta Pertamina Enduro(JPE) Tisya Amal...,SetterJakarta Pertamina Enduro ( JPE ) Tisya A...,SetterJakarta Pertamina Enduro JPE Tisya Ama...
4,Ducatimemberi wanti-wanti keHondamenjelang mus...,Ducatimemberi wanti-wanti keHondamenjelang mus...,Ducatimemberi wantiwanti keHondamenjelang musi...

#### pta.trunojoyo.ac.id

In [13]:
pta[["abstrak", "clean_no_stopword", "clean_no_symbol"]].head(5)

,abstrak,clean_no_stopword,clean_no_symbol
0,Sistem informasi akademik (SIAKAD) merupaka...,Sistem informasi akademik ( SIAKAD ) sistem in...,Sistem informasi akademik SIAKAD sistem info...
1,Berjalannya koneksi jaringan komputer dengan l...,Berjalannya koneksi jaringan komputer lancar g...,Berjalannya koneksi jaringan komputer lancar g...
2,Web server adalah sebuah perangkat lunak serve...,Web server perangkat lunak server berfungsi me...,Web server perangkat lunak server berfungsi me...
3,Seiring perkembangan teknologi yang ada diduni...,"Seiring perkembangan teknologi didunia , muncu...",Seiring perkembangan teknologi didunia muncul...
4,Penjadwalan kuliah di Perguruan Tinggi me...,Penjadwalan kuliah Perguruan kompleks . permas...,Penjadwalan kuliah Perguruan kompleks permasa...

### Cek Ejaan & Pembukaan Kata

Melakukan *spell checking* untuk memperbaiki kesalahan ejaan
dengan bantuan kamus bahasa Indonesia.

In [14]:
from spellchecker import SpellChecker
from tqdm import tqdm

# aktifkan tqdm untuk pandas
tqdm.pandas()

spell = SpellChecker(language=None, case_sensitive=False)
spell.word_frequency.load_text_file("./kamus_indonesia.txt") 

cache = {}

def correct_spelling(text):
    corrected = []
    for word in str(text).split():
        if word in cache:
            correction = cache[word]
        else:
            correction = spell.correction(word)
            cache[word] = correction if correction else word
        corrected.append(cache[word])
    return " ".join(corrected)

# gunakan progress_apply supaya ada progress bar
detik["clean_spellcheck"] = detik["clean_no_symbol"].progress_apply(correct_spelling)
pta["clean_spellcheck"]   = pta["clean_no_symbol"].progress_apply(correct_spelling)

100%|██████████| 100/100 [39:24<00:00, 23.64s/it]
100%|██████████| 2286/2286 [2:05:02<00:00,  3.28s/it]

### hasil spell checking

#### berita

In [21]:
detik[["Isi Berita", "clean_no_stopword", "clean_no_symbol", "clean_spellcheck"]].head(5)

,Isi Berita,clean_no_stopword,clean_no_symbol,clean_spellcheck
0,Marcus Fernaldi Gideonhadir di PelatnasPBSI. K...,Marcus Fernaldi Gideonhadir PelatnasPBSI . Ked...,Marcus Fernaldi Gideonhadir PelatnasPBSI Keda...,Marcus Fernaldi Gideonhadir PelatnasPBSI Kedat...
1,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...
2,"Tahun ini, tim Pertamina Jakarta Pertamina End...",", tim Pertamina Jakarta Pertamina Enduro ( JPE...",tim Pertamina Jakarta Pertamina Enduro JPE ...,air pertama Jakarta pertama Enduro apa menguki...
3,SetterJakarta Pertamina Enduro(JPE) Tisya Amal...,SetterJakarta Pertamina Enduro ( JPE ) Tisya A...,SetterJakarta Pertamina Enduro JPE Tisya Ama...,SetterJakarta pertama Enduro apa bisa Amallya ...
4,Ducatimemberi wanti-wanti keHondamenjelang mus...,Ducatimemberi wanti-wanti keHondamenjelang mus...,Ducatimemberi wantiwanti keHondamenjelang musi...,Ducatimemberi wantiwanti keHondamenjelang musi...

#### pta.trunojoyo.ac.id

In [22]:
pta[["abstrak", "clean_no_stopword", "clean_no_symbol", "clean_spellcheck"]].head(5)

,abstrak,clean_no_stopword,clean_no_symbol,clean_spellcheck
0,Sistem informasi akademik (SIAKAD) merupaka...,Sistem informasi akademik ( SIAKAD ) sistem in...,Sistem informasi akademik SIAKAD sistem info...,Sistem informasi akademik SIAKAD sistem inform...
1,Berjalannya koneksi jaringan komputer dengan l...,Berjalannya koneksi jaringan komputer lancar g...,Berjalannya koneksi jaringan komputer lancar g...,Berjalannya koneksi jangan komputer latar gang...
2,Web server adalah sebuah perangkat lunak serve...,Web server perangkat lunak server berfungsi me...,Web server perangkat lunak server berfungsi me...,Web server perangkat guna server berfungsi men...
3,Seiring perkembangan teknologi yang ada diduni...,"Seiring perkembangan teknologi didunia , muncu...",Seiring perkembangan teknologi didunia muncul...,sering pengembangan teknologi didunia muncul t...
4,Penjadwalan kuliah di Perguruan Tinggi me...,Penjadwalan kuliah Perguruan kompleks . permas...,Penjadwalan kuliah Perguruan kompleks permasa...,Penjadwalan kuliah Perguruan kompleks permasal...

### Stemming

Melakukan *stemming* untuk mengubah kata ke bentuk dasarnya, 
misalnya "berlari" -> "lari", "mengajar" -> "ajar".

In [18]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemming_text(text):
    return stemmer.stem(str(text))

detik["clean_stemmed"] = detik["clean_spellcheck"].apply(stemming_text)
pta["clean_stemmed"]   = pta["clean_spellcheck"].apply(stemming_text)

### hasil stemming

#### berita

In [25]:
detik[["Isi Berita", "clean_no_stopword", "clean_no_symbol", "clean_spellcheck", "clean_stemmed"]].head(5)

,Isi Berita,clean_no_stopword,clean_no_symbol,clean_spellcheck,clean_stemmed
0,Marcus Fernaldi Gideonhadir di PelatnasPBSI. K...,Marcus Fernaldi Gideonhadir PelatnasPBSI . Ked...,Marcus Fernaldi Gideonhadir PelatnasPBSI Keda...,Marcus Fernaldi Gideonhadir PelatnasPBSI Kedat...,marcus fernaldi gideonhadir pelatnaspbsi datan...
1,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...,megawati hangestri pertiwimembawared sparksmer...
2,"Tahun ini, tim Pertamina Jakarta Pertamina End...",", tim Pertamina Jakarta Pertamina Enduro ( JPE...",tim Pertamina Jakarta Pertamina Enduro JPE ...,air pertama Jakarta pertama Enduro apa menguki...,air pertama jakarta pertama enduro apa ukir pr...
3,SetterJakarta Pertamina Enduro(JPE) Tisya Amal...,SetterJakarta Pertamina Enduro ( JPE ) Tisya A...,SetterJakarta Pertamina Enduro JPE Tisya Ama...,SetterJakarta pertama Enduro apa bisa Amallya ...,setterjakarta pertama enduro apa bisa amallya ...
4,Ducatimemberi wanti-wanti keHondamenjelang mus...,Ducatimemberi wanti-wanti keHondamenjelang mus...,Ducatimemberi wantiwanti keHondamenjelang musi...,Ducatimemberi wantiwanti keHondamenjelang musi...,ducatimemberi wantiwanti kehondamenjelang musi...

#### pta.tunojoyo.ac.id

In [26]:
pta[["abstrak", "clean_no_stopword", "clean_no_symbol", "clean_spellcheck", "clean_stemmed"]].head(5)

,abstrak,clean_no_stopword,clean_no_symbol,clean_spellcheck,clean_stemmed
0,Sistem informasi akademik (SIAKAD) merupaka...,Sistem informasi akademik ( SIAKAD ) sistem in...,Sistem informasi akademik SIAKAD sistem info...,Sistem informasi akademik SIAKAD sistem inform...,sistem informasi akademik siakad sistem inform...
1,Berjalannya koneksi jaringan komputer dengan l...,Berjalannya koneksi jaringan komputer lancar g...,Berjalannya koneksi jaringan komputer lancar g...,Berjalannya koneksi jangan komputer latar gang...,jalan koneksi jangan komputer latar ganggu har...
2,Web server adalah sebuah perangkat lunak serve...,Web server perangkat lunak server berfungsi me...,Web server perangkat lunak server berfungsi me...,Web server perangkat guna server berfungsi men...,web server perangkat guna server fungsi terima...
3,Seiring perkembangan teknologi yang ada diduni...,"Seiring perkembangan teknologi didunia , muncu...",Seiring perkembangan teknologi didunia muncul...,sering pengembangan teknologi didunia muncul t...,sering kembang teknologi dunia muncul teknolog...
4,Penjadwalan kuliah di Perguruan Tinggi me...,Penjadwalan kuliah Perguruan kompleks . permas...,Penjadwalan kuliah Perguruan kompleks permasa...,Penjadwalan kuliah Perguruan kompleks permasal...,jadwal kuliah guru kompleks masalah variabel t...

### Tokenisasi

Melakukan *tokenisasi* agar teks dipecah menjadi daftar kata per dokumen

In [27]:
def tokenize(text):
    return word_tokenize(str(text))

detik["tokenized"] = detik["clean_stemmed"].apply(tokenize)
pta["tokenized"]   = pta["clean_stemmed"].apply(tokenize)

### Hasil tokenisasi

#### berita

In [30]:
detik[["Isi Berita", "clean_no_stopword", "clean_no_symbol", "clean_spellcheck", "clean_stemmed", "tokenized"]].head(5)

,Isi Berita,clean_no_stopword,clean_no_symbol,clean_spellcheck,clean_stemmed,tokenized
0,Marcus Fernaldi Gideonhadir di PelatnasPBSI. K...,Marcus Fernaldi Gideonhadir PelatnasPBSI . Ked...,Marcus Fernaldi Gideonhadir PelatnasPBSI Keda...,Marcus Fernaldi Gideonhadir PelatnasPBSI Kedat...,marcus fernaldi gideonhadir pelatnaspbsi datan...,"[marcus, fernaldi, gideonhadir, pelatnaspbsi, ..."
1,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...,Megawati Hangestri PertiwimembawaRed Sparksmer...,megawati hangestri pertiwimembawared sparksmer...,"[megawati, hangestri, pertiwimembawared, spark..."
2,"Tahun ini, tim Pertamina Jakarta Pertamina End...",", tim Pertamina Jakarta Pertamina Enduro ( JPE...",tim Pertamina Jakarta Pertamina Enduro JPE ...,air pertama Jakarta pertama Enduro apa menguki...,air pertama jakarta pertama enduro apa ukir pr...,"[air, pertama, jakarta, pertama, enduro, apa, ..."
3,SetterJakarta Pertamina Enduro(JPE) Tisya Amal...,SetterJakarta Pertamina Enduro ( JPE ) Tisya A...,SetterJakarta Pertamina Enduro JPE Tisya Ama...,SetterJakarta pertama Enduro apa bisa Amallya ...,setterjakarta pertama enduro apa bisa amallya ...,"[setterjakarta, pertama, enduro, apa, bisa, am..."
4,Ducatimemberi wanti-wanti keHondamenjelang mus...,Ducatimemberi wanti-wanti keHondamenjelang mus...,Ducatimemberi wantiwanti keHondamenjelang musi...,Ducatimemberi wantiwanti keHondamenjelang musi...,ducatimemberi wantiwanti kehondamenjelang musi...,"[ducatimemberi, wantiwanti, kehondamenjelang, ..."

#### pta.trunojoyo.ac.id

In [31]:
pta[["abstrak", "clean_no_stopword", "clean_no_symbol", "clean_spellcheck", "clean_stemmed", "tokenized"]].head(5)

,abstrak,clean_no_stopword,clean_no_symbol,clean_spellcheck,clean_stemmed,tokenized
0,Sistem informasi akademik (SIAKAD) merupaka...,Sistem informasi akademik ( SIAKAD ) sistem in...,Sistem informasi akademik SIAKAD sistem info...,Sistem informasi akademik SIAKAD sistem inform...,sistem informasi akademik siakad sistem inform...,"[sistem, informasi, akademik, siakad, sistem, ..."
1,Berjalannya koneksi jaringan komputer dengan l...,Berjalannya koneksi jaringan komputer lancar g...,Berjalannya koneksi jaringan komputer lancar g...,Berjalannya koneksi jangan komputer latar gang...,jalan koneksi jangan komputer latar ganggu har...,"[jalan, koneksi, jangan, komputer, latar, gang..."
2,Web server adalah sebuah perangkat lunak serve...,Web server perangkat lunak server berfungsi me...,Web server perangkat lunak server berfungsi me...,Web server perangkat guna server berfungsi men...,web server perangkat guna server fungsi terima...,"[web, server, perangkat, guna, server, fungsi,..."
3,Seiring perkembangan teknologi yang ada diduni...,"Seiring perkembangan teknologi didunia , muncu...",Seiring perkembangan teknologi didunia muncul...,sering pengembangan teknologi didunia muncul t...,sering kembang teknologi dunia muncul teknolog...,"[sering, kembang, teknologi, dunia, muncul, te..."
4,Penjadwalan kuliah di Perguruan Tinggi me...,Penjadwalan kuliah Perguruan kompleks . permas...,Penjadwalan kuliah Perguruan kompleks permasa...,Penjadwalan kuliah Perguruan kompleks permasal...,jadwal kuliah guru kompleks masalah variabel t...,"[jadwal, kuliah, guru, kompleks, masalah, vari..."

### Saving Procesing

Hasil preprocessing disimpan dalam file CSV baru:

- detik_cleaned.csv
- pta_cleaned.csv

In [32]:
detik.to_csv("detik_cleaned.csv", index=False)
pta.to_csv("pta_cleaned.csv", index=False)

print("Preprocessing selesai! Hasil disimpan di detik_cleaned.csv dan pta_cleaned.csv")

Preprocessing selesai! Hasil disimpan di detik_cleaned.csv dan pta_cleaned.csv